version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *
      MYSQL_DATABASE: events
      MYSQL_USER: *
      MYSQL_PASSWORD: *
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
    driver: local
